# Generated by Django 3.1.1 on 2021-07-09 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstaProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InstagramUserNameCustomer', models.CharField(max_length=200)),
                ('BusinessName', models.CharField(max_length=200)),
                ('InstagramPassword', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Province', models.CharField(max_length=200)),
                ('PostalCode', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followerUsername', models.CharField(max_length=200)),
                ('InstagramLink', models.CharField(max_length=200)),
                ('RelevancyScore', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('PostalCode', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('InstagramUserNameCustomer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='CurrentDashboard.instaprofiles')),
            ],
        ),
    ]
