# Generated by Django 3.1.1 on 2021-07-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurrentDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='lastActivity',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
