# Generated by Django 3.1.1 on 2021-07-09 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CurrentDashboard', '0002_followers_lastactivity'),
    ]


