# Generated by Django 3.1.1 on 2021-07-11 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CurrentDashboard', '0004_auto_20210710_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='InstagramLink',
            new_name='instagramLink',
        ),
        migrations.RenameField(
            model_name='followers',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='followers',
            old_name='PostalCode',
            new_name='relevancyScore',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='RelevancyScore',
        ),
        migrations.CreateModel(
            name='targets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetUsername', models.CharField(max_length=200)),
                ('instagramLink', models.CharField(max_length=200)),
                ('relevancyScore', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('lastActivity', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('InstagramUserNameCustomer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='CurrentDashboard.instaprofiles')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInteractionsOnTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interactionType', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('InstagramTarget', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='CurrentDashboard.targets')),
                ('InstagramUserNameCustomer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='CurrentDashboard.instaprofiles')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInteractionsOnFollowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interactionType', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('InstagramFollower', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='CurrentDashboard.followers')),
                ('InstagramUserNameCustomer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='CurrentDashboard.instaprofiles')),
            ],
        ),
    ]
