# Generated by Django 3.1.1 on 2021-07-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurrentDashboard', '0006_auto_20210712_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='instaprofiles',
            name='totalFollowers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='instaprofiles',
            name='totalFollowing',
            field=models.IntegerField(null=True),
        ),
    ]
