# Generated by Django 3.1.1 on 2021-07-14 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CurrentDashboard', '0007_auto_20210714_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instaprofiles',
            name='totalFollowers',
        ),
        migrations.RemoveField(
            model_name='instaprofiles',
            name='totalFollowing',
        ),
        migrations.CreateModel(
            name='profileDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalFollowing', models.IntegerField(null=True)),
                ('totalFollowers', models.IntegerField(null=True)),
                ('tips', models.CharField(max_length=200)),
                ('lastNotification', models.CharField(max_length=200)),
                ('lastActivity', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('InstagramUserNameCustomer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='CurrentDashboard.instaprofiles')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
