# Generated by Django 3.1.1 on 2021-07-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CurrentDashboard', '0008_auto_20210714_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledesc',
            name='InstagramUserNameCustomer',
        ),
    ]
