# Generated by Django 3.1.1 on 2021-07-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CurrentDashboard', '0009_remove_profiledesc_instagramusernamecustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledesc',
            name='totalFollowers',
        ),
        migrations.RemoveField(
            model_name='profiledesc',
            name='totalFollowing',
        ),
    ]
