# Generated by Django 3.1.1 on 2021-07-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurrentDashboard', '0010_auto_20210714_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledesc',
            name='totalFollowers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profiledesc',
            name='totalFollowing',
            field=models.IntegerField(null=True),
        ),
    ]
