# Generated by Django 3.1.1 on 2021-07-15 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CurrentDashboard', '0011_auto_20210714_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newfollowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followerUsername', models.CharField(max_length=200)),
                ('instagramLink', models.CharField(max_length=200)),
                ('relevancyScore', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('lastActivity', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('InstagramUserNameCustomer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='CurrentDashboard.instaprofiles')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
