# Generated by Django 3.1.1 on 2021-07-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurrentDashboard', '0012_newfollowers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledesc',
            name='totalInteractionsyouGot',
            field=models.IntegerField(null=True),
        ),
    ]
