# Generated by Django 3.1.1 on 2021-07-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurrentDashboard', '0013_profiledesc_totalinteractionsyougot'),
    ]

    operations = [
        migrations.AddField(
            model_name='newfollowers',
            name='interest',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
