# Generated by Django 3.1.1 on 2021-07-16 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CurrentDashboard', '0014_newfollowers_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newfollowers',
            name='interest',
        ),
    ]
