# Generated by Django 3.1.1 on 2021-07-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurrentDashboard', '0016_newfollowers_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinteractionsontarget',
            name='CountOfLikes',
            field=models.IntegerField(default=1),
        ),
    ]
