# Generated by Django 3.1.1 on 2021-07-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurrentDashboard', '0017_customerinteractionsontarget_countoflikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinteractionsonfollowers',
            name='CountOfLikes',
            field=models.IntegerField(default=1),
        ),
    ]
